Prefix: ' &8&l[&6&l亘古大陆&8&l] &7'
tip:
  - '&c&lTIP.&a&l当前享受会员折扣: &e&l<discount>'
  - ''
  - '&b&l抵制不良游戏，拒绝盗版游戏。 注意自我保护，谨防受骗上当。'
  - '&b&l适度游戏益脑，沉迷游戏伤身。 合理安排时间，享受健康生活。'
discount:
  vip: 0.9
  svp: 0.8
  mvp: 0.7
purchase-limit:
  goods_1: 1