name: JustStore
main: net.sakuragame.eternal.juststore.JustStore
version: ${project.version}
author: 'Justwei'
api-version: '1.13'
depend:
  - MegumiLib
  - DataManager
  - DragonCore
  - UIFactory
  - Zaphkiel

commands:
  jstore:
    aliases:
      - store
      - shop
    description: show all command